# Generated by Django 2.0.4 on 2019-05-07 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0002_auto_20190507_2001'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedbackresponse',
            name='feedback',
        ),
    ]
