# Generated by Django 2.0.4 on 2019-05-07 20:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0003_remove_feedbackresponse_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedbackresponse',
            name='feedback',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='feedback.Feedback'),
            preserve_default=False,
        ),
    ]
