# Generated by Django 2.0.4 on 2019-05-13 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0005_auto_20190513_1652'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='status',
            field=models.CharField(choices=[('already_exists', 'Issue Already Exists'), ('considering_ntf', 'Considering No Time Frame'), ('considering_tf', 'Considering With Time Frame'), ('working', 'Working'), ('complete', 'Complete'), ('not_valid', 'Not a Valid Issue'), ('none', 'No Status Assigned')], default='none', max_length=60),
        ),
    ]
