# Generated by Django 2.0.4 on 2019-05-29 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0006_auto_20190513_1657'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='is_urgent',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
