# Generated by Django 2.0.4 on 2019-08-28 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0009_auto_20190618_1948'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedbackresponse',
            name='is_company',
            field=models.BooleanField(default=False),
        ),
    ]
