# Generated by Django 3.0.7 on 2020-06-29 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0010_feedbackresponse_is_company'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='deleted',
        ),
        migrations.RemoveField(
            model_name='feedbackresponse',
            name='deleted',
        ),
    ]
